---
- hosts: 172.31.44.52 
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: install webserver
    apt: 
      name: apache2
      state: present

  - name: start my webserver
    service:
      name: apache2
      state: started

  - name: i want copy index.j2 file into nodes
    template:
      src:  myindex.j2
      dest: /var/www/html/index.html
  