---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install java on ubuntu node
    apt:
      name: "{{myjavaonubuntu}}"
      state: present
    when: ansible_os_familly=="Debian"

  - name: install java on RedHat nodes
    yum:
      name: "{{myjavaonredhat}}"
      state: present
    when: ansible_os_familly=="RedHat"