---
- hosts: 172.31.44.52
  become: yes
  vars:
    myvar1: git
    myvar2: tree
    myvar3: wget
    myjavaonubuntu: gitii
  tasks:
  - name: display vars1
    debug:
      msg: "{{myvar1}}"
  - name: install myjavaonubuntu
    apt:
      name: "{{myjavaonubuntu}}"
      state: present