---
- hosts: 172.31.44.52
  become: yes
  tasks:
  - name: install git task1
    apt:
      name: git
      state: present
    tags: mygit

  - name: install tree task2
    apt:
      name: tree
      stateee: present
    tags: mytree
    ignore_errors: yes

  - name: install wget task3
    apt:
       name: wget
       state: present
    tags: mywget